# 1. PyTorch Operation
## numpy + AutoGrad

### Numpy ndarray와 비슷하다

Torch는 numpy가 GPU를 쓸수 있는 데이터 형식

In [1]:
import numpy as np

n_array = np.arange(10).reshape(2, 5)
print(n_array)
print("ndim :", n_array.ndim, "shape : ", n_array.shape)

[[0 1 2 3 4]
 [5 6 7 8 9]]
ndim : 2 shape :  (2, 5)


In [2]:
import torch

t_array = torch.FloatTensor(n_array)
print(t_array)
print("ndim :", t_array.ndim, "shape : ", t_array.shape)

tensor([[0., 1., 2., 3., 4.],
        [5., 6., 7., 8., 9.]])
ndim : 2 shape :  torch.Size([2, 5])


In [3]:
data = [[3, 5], [10, 5]]
x_data = torch.tensor(data)
x_data

tensor([[ 3,  5],
        [10,  5]])

In [7]:
x_data.device

device(type='cpu')

In [8]:
if torch.cuda.is_available():
    x_data_cuda = x_data.to("cuda")

x_data_cuda.device

device(type='cuda', index=0)

reshape (Copy) --> view (Reference)

1차원 삭제(압축) --> squeeze

1차원 추가 --> unsqueeze

In [11]:
tensor_ex = torch.rand(size=(2,3,2))
tensor_ex

tensor([[[0.8736, 0.0661],
         [0.8215, 0.5333],
         [0.9676, 0.5091]],

        [[0.3925, 0.4416],
         [0.6288, 0.6051],
         [0.0751, 0.9612]]])

In [12]:
tensor_ex.view([-1, 6])

tensor([[0.8736, 0.0661, 0.8215, 0.5333, 0.9676, 0.5091],
        [0.3925, 0.4416, 0.6288, 0.6051, 0.0751, 0.9612]])

In [13]:
tensor_ex.reshape([-1, 6])

tensor([[0.8736, 0.0661, 0.8215, 0.5333, 0.9676, 0.5091],
        [0.3925, 0.4416, 0.6288, 0.6051, 0.0751, 0.9612]])

기본적인 행렬, 스칼라 덧셈은 같다

dot (벡터간에는) --> mm (행렬 간에는)

mm vs matmul 
matmul은 알아서 차원은 맞추어 준다 (broadcasting).

nn.functional mod를 통해 다양한 수식 변환을 지원한다.

In [14]:
import torch
import torch.nn.functional as F

tensor = torch.FloatTensor([0.5, 0.7, 0.1])

h_tensor = F.softmax(tensor, dim=0)
h_tensor

tensor([0.3458, 0.4224, 0.2318])

In [16]:
y = torch.randint(5,(10,5))

y_label = y.argmax(dim=1)

y_label

tensor([1, 1, 4, 4, 4, 2, 1, 4, 1, 0])

In [17]:
torch.nn.functional.one_hot(y_label)

tensor([[0, 1, 0, 0, 0],
        [0, 1, 0, 0, 0],
        [0, 0, 0, 0, 1],
        [0, 0, 0, 0, 1],
        [0, 0, 0, 0, 1],
        [0, 0, 1, 0, 0],
        [0, 1, 0, 0, 0],
        [0, 0, 0, 0, 1],
        [0, 1, 0, 0, 0],
        [1, 0, 0, 0, 0]])

pyTorch의 핵심은 자동미분 --> backward

In [18]:
w = torch.tensor(2.0, requires_grad=True)

y = w ** 2

z = 10 * y + 2

z.backward()
w.grad

tensor(40.)